package bank.app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * This class is what allows us to initiate a JavaFX GUI. 
 * It loads the LoginForm JavaFX, which will then allow users to navigate
 * to other files.
 */
public class GuiMain extends Application {

    @Override
    /**
     * Initializes and displays the primary stage (the main window), which in this case is
     * the LoginForm.
     *
     * @param stage the primary stage generated by JavaFX at runtime
     * @throws Exception is thrown if the FXML file or resources fail to load
     */
    public void start(Stage stage) throws Exception {

        FXMLLoader loader = new FXMLLoader(
                GuiMain.class.getResource("/bank/Views/LoginForm.fxml")
        );

        Scene scene = new Scene(loader.load(), 900, 700);

        scene.getStylesheets().add(
                GuiMain.class.getResource("/bank/css/login.css").toExternalForm()
        );

        stage.setTitle("MyBankUML Login");
        stage.setScene(scene);
        stage.setResizable(false);
        stage.show();
    }

    /**
     * The main is used in this class to launch the JavaFX GUI.
     *
     * @param args string array of arguments
     */
    public static void main(String[] args) {
        launch();
    }
}